development:
  database: ace-magent-development
  host: localhost
  port: 27017
  websocket_channel: magent.websocket

test:
  database: ace-test

production:
  database: ace-magent-production
  websocket_channel: magent.websocket

