local:
  database: qna-magent-development
  host: localhost
  port: 27017
  websocket_channel: magent.websocket

development:
  database: qna-magent-development
  host: localhost
  port: 27017
  websocket_channel: magent.websocket

test:
  database: qna-test

production:
  database: qna-magent-production
  websocket_channel: magent.websocket

