# See https://github.com/ryanb/xapit/wiki/Configuration
development:
  database_path: "db/xapit"
  server: "http://localhost:9292"

local:
  database_path: "db/xapit"
  enabled: true
  server: "http://localhost:9292"
  spelling: true

test:
  enabled: false
  spelling: false

production:
  database_path: "db/xapit"
  server: "http://localhost:9292"
