#!/usr/bin/env ruby
# -*- mode: ruby -*-

ENV['Rails.env'] ||= (ARGV.first || 'development')
require File.expand_path("../../config/environment", __FILE__)

puts Solr.update(Question.all.map{|q| Solr.add_document(q)}, true).body
