#!/usr/bin/env ruby

ENV['Rails.env'] ||= (ARGV.first || 'development')
require File.expand_path("../../config/environment", __FILE__)

tags = {}

Membership.all.each do |member|
  member.preferred_tags.each do |tag|
    tags[tag] ||= []
    tags[tag] << member.display_name
  end
end

tag_names = tags.keys

max_length = tag_names.inject(0) { |l, t| [l, t.length].max }

tag_names.sort.each do |tag|
  printf "%-#{max_length + 2}s|  %s\n", tag, tags[tag].sort.join(", ")
end

puts "\n========================================"
puts "The following tags do not have followers:\n"
puts

puts Tag.all.map {|tag| tag.name}.select {|tag| !tag_names.include?(tag) }.sort.join(", ")
